<?= $this->doctype()."\n" ?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?= $this->headMeta()."\n" ?>
    <?= $this->headTitle()."\n" ?>
    <link href="/assets/css/exception.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="noaccess">
        <p class="error-404 error-title">  <?= $this->title ?></p>
        <p class="error-404 error-explain"><?= $this->text ?></p>
        <p class="error-404 error-explain"> retour à l' <a href="/">ACCUEIL</a></p>
    </div>
</body>
</html>
